version: "3.8"

services:
  gemini-gpt:
    image: penggan0/rss-full:latest
    restart: unless-stopped
    volumes:
      - ./gpt.py:/app/gpt.py       # 挂载 Python 脚本
      - ./.env:/app/.env           # 挂载环境变量
      - ./chats.db:/app/chats.db   # 挂载数据库
    command: python gpt.py         # 运行脚本
    deploy:
      resources:
        limits:
          memory: 112M
          cpus: "0.5"

  qq:
    image: penggan0/rss-full:latest  # 使用同一个镜像
    restart: unless-stopped
    volumes:
      - ./qq.py:/app/qq.py          # 挂载 Python 脚本
      - ./.env:/app/.env            # 挂载环境变量
      - ./translator.db:/app/translator.db  # 挂载数据库
    command: python qq.py           # 运行脚本
    deploy:
      resources:
        limits:
          memory: 106M
          cpus: "0.3"