version: '3.8'

services:
  rss:
    build: .
    platform: linux/amd64  # 可以根据需要更改
    restart: unless-stopped
    volumes:
      - ./:/app  # 挂载整个rss目录
    environment:
      - ENV_FILE=/app/.env
    command: python rss.py  # 默认运行rss.py，可以根据需要修改

  # 可以添加其他服务，如mail、gemini等
  mail:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
    environment:
      - ENV_FILE=/app/.env
    command: python mail.py

  # 其他服务类似配置...